from argparse import Namespace

def ptb_softmax():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=20, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=False,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.3,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=0.0, gs_smax_k=2.0,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        nemb=400, nhid=1150, nhidlast=400,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        seed=141, single_gpu=True,
        small_batch_size=20, switch_epoch=200,
        test_batch_size=1, tied=True,
        tied_wdecay=2.4e-06, top_model='smax',
        wdecay=1.2e-06, wdrop=0.5,
        spectrum_control=False, 
        save=''
    )



def ptb_ss():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=20, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.3,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=0.0, gs_smax_k=2.0,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        nemb=400, nhid=1150, nhidlast=400,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        save='',
        seed=141, single_gpu=True,
        small_batch_size=20, switch_epoch=200,
        test_batch_size=1, tied=True,
        tied_wdecay=2.4e-06,
        top_model='s_smax', wdecay=1.2e-06,
        wdrop=0.5, spectrum_control=False
    )

def ptb_gss():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=20, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.3,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=-1.5, gs_smax_k=2.5,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        mos_dropoutl=0.0, mos_nexpert=1,
        nemb=400, nhid=1150, nhidlast=400,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_freeze=False,
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_patch='', plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        save='',
        seed=141, shift_smax_s=0.0,
        single_gpu=True, small_batch_size=20,
        switch_epoch=200, test_batch_size=1,
        tied=True, tied_wdecay=2.4e-06,
        top_model='gs_smax', wdecay=1.2e-06,
        wdrop=0.5, spectrum_control=False
    )

def ptb_lms_plif():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=20, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.3,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=0.0, gs_smax_k=2.0,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        nemb=400, nhid=1150, nhidlast=400,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        save='',
        seed=141, single_gpu=True,
        small_batch_size=20, switch_epoch=200,
        test_batch_size=1, tied=True,
        tied_wdecay=2.4e-06,
        top_model='plif_smax', wdecay=1.2e-06,
        wdrop=0.5, spectrum_control=False,
        plif_smax_patch='', plif_smax_freeze=False
    )

def ptb_moc_etasgd():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=12, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross',
        ctx_noise_scale=0.15, cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.225,
        dropouti=0.4, emb_freeze=False,
        emb_noise_scale=0.15, emb_patch='',
        epochs=1000, eval_batch_size=10,
        flood_b=None, gs_smax_c=0.0,
        gs_smax_k=2.0, local_debug=False,
        log_interval=200, lr=20.0,
        max_seq_len_delta=40,
        mos_dropoutl=0.29, mos_nexpert=15,
        mt_add_noise=False, mt_dropoutc=0.0,
        mt_dropoutg=0.0, mt_ngate=160,
        mt_nmix=4, mt_noise_stdev=0.1,
        nemb=280, nhid=960, nhidlast=620,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_freeze=False,
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_patch='', plif_smax_t=20,
        plif_smax_w_variance=1.0,
        recent_model_analysis=False,
        rnn_type='LSTM',
        save='',
        save_recent=False,
        sc_smax_gsv_dist_path=None,
        sc_smax_sv_rc=0.1,
        sc_smax_u_fn_rc=0.01,
        sc_smax_u_sm_rc=100,
        sc_smax_u_sn_rc=0.01,
        sc_smax_v_fn_rc=0.01,
        sc_smax_v_sm_rc=100,
        sc_smax_v_sn_rc=0.01, seed=28,
        shift_smax_s=0.0, single_gpu=True,
        small_batch_size=12,
        spectrum_control=False,
        switch_epoch=200, test_batch_size=1,
        tied=True, tied_lr=-1,
        tied_wdecay=2.4e-06, top_model='moc',
        wdecay=1.2e-06, wdrop=0.5,
        xmoc_dropoutl=0.0, xmoc_gss_c=0.0,
        xmoc_gss_flip=False, xmoc_gss_k=2.0,
        xmoc_gss_mix=False, xmoc_nexpert=1,
        xmos_dropoutl=0.0, xmos_gss_c=0.0,
        xmos_gss_k=2.0, xmos_nexpert=1
    )

def ptb_moc_ntasgd():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=12, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross',
        ctx_noise_scale=0.15, cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.225,
        dropouti=0.4, emb_freeze=False,
        emb_noise_scale=0.15, emb_patch='',
        epochs=1000, eval_batch_size=10,
        flood_b=None, gs_smax_c=0.0,
        gs_smax_k=2.0, local_debug=False,
        log_interval=200, lr=20.0,
        max_seq_len_delta=40,
        mos_dropoutl=0.29, mos_nexpert=15,
        mt_add_noise=False, mt_dropoutc=0.0,
        mt_dropoutg=0.0, mt_ngate=160,
        mt_nmix=4, mt_noise_stdev=0.1,
        nemb=280, nhid=960, nhidlast=620,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_freeze=False,
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_patch='', plif_smax_t=20,
        plif_smax_w_variance=1.0,
        recent_model_analysis=False,
        rnn_type='LSTM',
        save='',
        save_recent=False,
        sc_smax_gsv_dist_path=None,
        sc_smax_sv_rc=0.1,
        sc_smax_u_fn_rc=0.01,
        sc_smax_u_sm_rc=100,
        sc_smax_u_sn_rc=0.01,
        sc_smax_v_fn_rc=0.01,
        sc_smax_v_sm_rc=100,
        sc_smax_v_sn_rc=0.01, seed=28,
        shift_smax_s=0.0, single_gpu=True,
        small_batch_size=12,
        spectrum_control=False,
        switch_epoch=-1, test_batch_size=1,
        tied=True, tied_lr=-1,
        tied_wdecay=2.4e-06, top_model='moc',
        wdecay=1.2e-06, wdrop=0.5,
        xmoc_dropoutl=0.0, xmoc_gss_c=0.0,
        xmoc_gss_flip=False, xmoc_gss_k=2.0,
        xmoc_gss_mix=False, xmoc_nexpert=1,
        xmos_dropoutl=0.0, xmos_gss_c=0.0,
        xmos_gss_k=2.0, xmos_nexpert=1
    )

def ptb_mos_etasgd():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=12, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.225,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=0.0, gs_smax_k=2.0,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        mos_dropoutl=0.29, mos_nexpert=15,
        nemb=280, nhid=960, nhidlast=620,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_freeze=False,
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_patch='', plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        save='',
        seed=28, shift_smax_s=0.0,
        single_gpu=True, small_batch_size=12,
        switch_epoch=200, test_batch_size=1,
        tied=True, tied_wdecay=2.4e-06,
        top_model='mos', wdecay=1.2e-06,
        wdrop=0.5, spectrum_control=False
    )


def ptb_mos_ntasgd():
    return Namespace(adv_smax_alpha=0.005,
        alpha=2, base_model='dai',
        batch_size=12, beta=1, bptt=70,
        clip=0.25, continue_from_epoch=1000,
        continue_train=False,
        criterion='cross', cuda=True,
        data='data/penn', decay_tied=False,
        detect_anomaly=False, dropout=0.4,
        dropoute=0.1, dropouth=0.225,
        dropouti=0.4, emb_noise_scale=0.15,
        epochs=1000, eval_batch_size=10,
        gs_smax_c=0.0, gs_smax_k=2.0,
        local_debug=False, log_interval=200,
        lr=20.0, max_seq_len_delta=40,
        mos_dropoutl=0.29, mos_nexpert=15,
        nemb=280, nhid=960, nhidlast=620,
        nlayer=3, no_analysis=False,
        no_comet=False, no_switch=False,
        noisy_emb=False, nonmono=5,
        ntoken=10000, optimizer='sgd',
        plif_smax_freeze=False,
        plif_smax_k=100000, plif_smax_lr=0.02,
        plif_smax_patch='', plif_smax_t=20,
        plif_smax_w_variance=1.0,
        rnn_type='LSTM',
        save='',
        seed=28, shift_smax_s=0.0,
        single_gpu=True, small_batch_size=12,
        switch_epoch=-1, test_batch_size=1,
        tied=True, tied_wdecay=2.4e-06,
        top_model='mos', wdecay=1.2e-06,
        wdrop=0.5, spectrum_control=False
    )